os: linux
dist: xenial
language: cpp
compiler: clang
services:
- docker
before_install: |
  echo '##### CHECKPOINT 1'
# EOSIO
script: |
  echo '##### CHECKPOINT 2'
  docker pull eosio/contracts-builder:latest
  docker run --rm eosio/contracts-builder:latest bash -c "echo 'Yeet!'"
after_success: |
  echo '##### CHECKPOINT 3'