steps:
  
  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "bash ./.cicd/run.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      ENABLE_BUILD: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18

  - wait

  - label: ":ubuntu: Ubuntu 18.04 - Test"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' && tar -xzf build.tar.gz"
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      ENABLE_TEST: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18
